apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: toggle-master
type: Opaque
data:
  # base64: 123456678
  postgres-password: MTIzNDU2Njc4
  # base64: admin-secreto-123
  master-key: YWRtaW4tc2VjcmV0by0xMjM=
  # base64: postgres://teste:auth_password@dev-auth-service-db.cahgwak00ah1.us-east-1.rds.amazonaws.com:5432/teste?sslmode=require
  database-url: cG9zdGdyZXM6Ly90ZXN0ZTphdXRoX3Bhc3N3b3JkQGRldi1hdXRoLXNlcnZpY2UtZGIuY2FoZ3dhazAwYWgxLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3Rlc3RlP3NzbG1vZGU9cmVxdWlyZQ==