app:
  name: evaluation-service

namespace: toggle-master

replicaCount: 2

image:
  repository: 581571885952.dkr.ecr.us-east-1.amazonaws.com/toggle-master/evaluation-service
  tag: v1.0.0-f3fd4a3
  pullPolicy: IfNotPresent

service:
  port: 8004

configMap:
  name: evaluation-service-config

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 2

  startup:
    path: /health
    failureThreshold: 30
    periodSeconds: 5

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi